BXMSDOC-37917.2 RN- 7.2.1 RN update
emmurphy1/kie-docs pull request #148
Opened 2019-02-11 18:12 UTC by emmurphy1

Added Fixed in 7.2.1 chapter

[RHDM draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-3791-dm/#rn-721-fixed-issues-ref)
[RHPAM draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-3791-pam/#rn-721-fixed-issues-ref)

2019-02-12 12:18 UTC, krisv requested changes

2019-02-12 12:18 UTC, krisv commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Add https support to Openshift images [https://issues.jboss.org/browse/RHPAM-1814[RHPAM-1814]]
Add https support to smart router for OpenShift images?

2019-02-12 12:18 UTC, krisv commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Add support for Red Had  kie-server and controller in update tool. [https://issues.jboss.org/browse/RHPAM-1824[RHPAM-1824]]
Red Hat ;)

2019-02-13 05:57 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* The BRL condition `is contained in the (comma separated) list` does not produce a multi-select drop down in the guided decision table or guided rule template[https://issues.jboss.org/browse/RHDM-48
```suggestion
* The BRL condition `is contained in the (comma separated) list` does not produce a multi-select drop down in the guided decision table or guided rule template [https://issues.jboss.org/browse/RHDM-483[RHDM-483]]
```

2019-02-13 05:57 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Incremental compilation fails when calling static method in RHS[https://issues.jboss.org/browse/RHPAM-1453[RHPAM-1453]]
```suggestion
* Incremental compilation fails when calling static method in RHS [https://issues.jboss.org/browse/RHPAM-1453[RHPAM-1453]]
```

2019-02-13 05:57 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* {KIE_SERVER} loses connection to {CENTRAL}[https://issues.jboss.org/browse/RHPAM-1718[RHPAM-1718]]
```suggestion
* {KIE_SERVER} loses connection to {CENTRAL} [https://issues.jboss.org/browse/RHPAM-1718[RHPAM-1718]]
```

2019-02-13 05:57 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Add https support to Smart Router OpenShift images[https://issues.jboss.org/browse/RHPAM-1814[RHPAM-1814]]
```suggestion
* Add https support to Smart Router OpenShift images [https://issues.jboss.org/browse/RHPAM-1814[RHPAM-1814]]
```

2019-02-13 05:57 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Cannot attach boundary events to service tasks in the new process designer [https://issues.jboss.org/browse/RHPAM-1667[RHPAM-1773]]
```suggestion
* Cannot attach boundary events to service tasks in the new process designer [https://issues.jboss.org/browse/RHPAM-1773[RHPAM-1773]]
```

2019-02-13 05:57 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Cannot set a sub-process process from different project as reusable [https://issues.jboss.org/browse/RHPAM-1667[RHPAM-1773]]
```suggestion
* Cannot set a sub-process process from different project as reusable [https://issues.jboss.org/browse/RHPAM-1667[RHPAM-1667]]
```

2019-02-13 12:44 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Cannot set a sub-process process from different project as reusable [https://issues.jboss.org/browse/RHPAM-1667[RHPAM-1773]]
Incorrect link.

2019-02-13 12:45 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Cannot attach boundary events to service tasks in the new process designer [https://issues.jboss.org/browse/RHPAM-1667[RHPAM-1773]]
Incorrect link.

2019-02-13 12:46 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Add https support to Smart Router OpenShift images[https://issues.jboss.org/browse/RHPAM-1814[RHPAM-1814]]
Missing space character.

2019-02-13 12:46 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* {KIE_SERVER} loses connection to {CENTRAL}[https://issues.jboss.org/browse/RHPAM-1718[RHPAM-1718]]
Missing space character.

2019-02-13 12:46 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Incremental compilation fails when calling static method in RHS[https://issues.jboss.org/browse/RHPAM-1453[RHPAM-1453]]
Missing space character.

2019-02-13 12:46 UTC, tomasdavidorg commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* The BRL condition `is contained in the (comma separated) list` does not produce a multi-select drop down in the guided decision table or guided rule template[https://issues.jboss.org/browse/RHDM-48
Missing space character.

2019-02-13 13:05 UTC, tomasdavidorg approved these changes

2019-02-13 13:49 UTC, sterobin reviewed
@emmurphy1 done. Minor tweaks. All links are good.

2019-02-13 13:49 UTC, sterobin commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* The BRL condition `is contained in the (comma separated) list` does not produce a multi-select drop down in the guided decision table or guided rule template [https://issues.jboss.org/browse/RHDM-4
"drop-down list" here and below (per IBM)

2019-02-13 13:49 UTC, sterobin commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Cannot set a sub-process process from different project as reusable [https://issues.jboss.org/browse/RHPAM-1667[RHPAM-1667]]
"Cannot set a sub-process from a different project as reusable"

2019-02-13 13:49 UTC, sterobin commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Add https support to Smart Router OpenShift images [https://issues.jboss.org/browse/RHPAM-1814[RHPAM-1814]]
"Add HTTPS support"

2019-02-13 13:49 UTC, sterobin commented on doc-content/enterprise-only/release-notes/rn-721-fixed-issues-ref.adoc
> +* Add support for {KIE_SERVER} and the controller in the update tool [https://issues.jboss.org/browse/RHPAM-1824[RHPAM-1824]]
"and the {CONTROLLER} in"

2019-04-02 16:13 UTC, closed without merging