BXMSDOC-6474 SpringBoot: Configuring Security
emmurphy1/kie-docs pull request #246
Opened 2020-09-18 13:23 UTC by emmurphy1

[BXMSDOC-6474](https://issues.redhat.com/browse/BXMSDOC-6474)

[PAM draft
](http://file.ork.redhat.com/~emmurphy/BXMSDOC-6474-pam/#security)
[DM draft](http://file.ork.redhat.com/~emmurphy/BXMSDOC-6474-dm/#security)

2020-10-02 07:41 UTC, afalhambra requested changes
Very good work @emmurphy1.

I've left some comments in the PR itself, not a big issue, only minor things.

Another thing I need to mention here is the following:

- CHAPTER 4. CONFIGURING THE BUSINESS APPLICATION WITH RED HAT SINGLE SIGN-ON
- Step 3.
It doesn't work straight away as per instructions. You need to have either that `${version.org.keycloak}` value already defined as a property in your pom.xml file or hardcoded to some keycloak version like `3.4.3.Final`

2020-10-02 07:41 UTC, afalhambra commented on doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc
> +                    .cors().and().csrf().disable() // Disable CORs & CSRF filters
Please remove comment, this is not needed here
```suggestion
                    .cors().and().csrf().disable()
```

2020-10-02 07:41 UTC, afalhambra commented on doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc
> +                    .and().headers().frameOptions().disable(); // Disable X-Frame header for h2-console
same here
```suggestion
                    .and().headers().frameOptions().disable();
```

2020-10-02 07:41 UTC, afalhambra commented on doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc
>  [source]
This is java source code
```suggestion
[source, java]
```

2020-10-08 18:18 UTC, emmurphy1 commented on doc-content/enterprise-only/springboot/bus-app-security-authorization-proc.adoc
> +    @Override  // (1)
Yes, I didn't see that comment in the code. Thanks.

2020-10-08 18:19 UTC, emmurphy1 commented on doc-content/enterprise-only/springboot/bus-app-security-authorization-proc.adoc
> +    @Override  // (1)
Fixed

2020-10-08 18:35 UTC, emmurphy1 commented on doc-content/enterprise-only/springboot/bus-app-security-disabling-proc.adoc
> +        //@formatter:off
Removed

2020-10-08 18:35 UTC, emmurphy1 commented on doc-content/enterprise-only/springboot/bus-app-security-disabling-proc.adoc
> +        // @formatter:on
Removed

2020-10-08 18:36 UTC, emmurphy1 commented on doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc
> +[source]
Fixed

2020-10-08 18:59 UTC, michelehaglund commented on doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc
> +A Realm manages a set of users, credentials, roles, and groups. A user belongs to and logs into a realm. Realms are isolated from one another and can only manage and authenticate the users that they
Should "Realm" be lower case?

2020-10-08 19:01 UTC, michelehaglund commented on doc-content/enterprise-only/springboot/bus-app-rh-sso_proc.adoc
> +. Add the following dependencies to the Spring Boot project `pom.xml` file:
project's?

Add the following dependencies to the Spring Boot project's `pom.xml` file:

2020-10-08 19:04 UTC, michelehaglund commented on doc-content/enterprise-only/springboot/bus-app-security-disabling-proc.adoc
> +. In the directory that contains your {PRODUCT} Spring Boot application, open the `business-application-service/src/main/java/com/company/service/DefaultWebSecurityConfig.java` file in a text editor
If this is the 1st instance of "IDE", please write it out: integrated development environment (IDE)

2020-10-08 19:08 UTC, michelehaglund commented on doc-content/enterprise-only/springboot/bus-app-security-disabling-proc.adoc
> +and populates the `SecurityContext` with the `anonymousUser` user with no designated roles other than the `ROLE_ANONYMOUS` role. The user will not have access to many of the features of the applicati
"they will be unable to action group assigned tasks." Seems like it should say something like "they will be unable to assign actions to group assigned tasks."

2020-10-08 19:10 UTC, michelehaglund commented on doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc
> +
Possible change to:

and have all of the permissions that they require without creating credentials for each user.

2020-10-08 19:13 UTC, michelehaglund approved these changes
I added a few comments.

2020-10-09 06:46 UTC, afalhambra requested changes

2020-10-09 06:46 UTC, afalhambra commented on doc-content/enterprise-only/springboot/bus-app-security-preauthenticate-proc.adoc
> +@Slf4j
@emmurphy1 Please remove this line. Thanks!
```suggestion
```

2020-10-09 15:04 UTC, emmurphy1 commented
@michelehaglund for some reason I am unable to comment on your comments, so here you go:
Add the following dependencies to the Spring Boot project's pom.xml file:
I'm trying to avoid anthropomorphism.

and have all of the permissions that they require without creating credentials for each user.
without requiring is vague (dangling participle, not sure. Anyway it's not clear who is responsible for creating (or not creating) the credentials

2020-10-12 17:41 UTC, closed without merging