BXMSDOC-8107 OptaPlanner Core Micrometer Metrics - BAPL-1986
emmurphy1/kie-docs pull request #329
Opened 2021-09-07 20:40 UTC by emmurphy1

2021-09-08 11:07 UTC, dupliaka commented on assemblies/assembly-planner-configuration.adoc
> +        String response = prometheusRegistry.scrape(); (1)
remove (1)

2021-09-08 15:07 UTC, briandooley requested changes

2021-09-09 19:11 UTC, Christopher-Chianelli requested changes
Note that most of these instructions are specific to Prometheus (Prometheus is the only registry officially supported by Quarkus; the other registries are from `io.quarkiverse.micrometer.registry` (https://search.maven.org/search?q=io.quarkiverse.micrometer.registry)).

2021-09-09 19:11 UTC, Christopher-Chianelli commented on assemblies/assembly-planner-configuration.adoc
> +. Add the following dependency to your application's `pom.xml` file where `<MONITORING_SYSTEM>` is a monitoring system supported by Micrometer:
Need to be supported by Quarkus AND Micrometer. Prometheus is the only registry supported by Quarkus currently.

2021-09-09 19:11 UTC, Christopher-Chianelli commented on assemblies/assembly-planner-configuration.adoc
> +management.endpoints.web.exposure.include=metrics,<MONITORING_SYSTEM>
The <MONITORING_SYSTEM> here and below are specific to Prometheus; see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export for details on how to set up the various registries. The other registries go to `/actuator/metrics`

2021-09-09 19:14 UTC, Christopher-Chianelli commented
As for why Prometheus is special, it the only registry that pull data from the application; the other registries expect the application to push data to it (thus they don't need an endpoint, but the application must know their endpoint).

2021-09-09 20:59 UTC, Christopher-Chianelli requested changes
Spring Boot has specific docs for micrometer configuration;

2021-09-09 20:59 UTC, Christopher-Chianelli commented on assemblies/assembly-planner-configuration.adoc
> +. Add configuration information to the application's `application.properties` file. For information, see the https://micrometer.io[Micrometer] web site.
For Spring Boot, the website is https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export

2021-09-09 20:59 UTC, Christopher-Chianelli commented on assemblies/assembly-planner-configuration.adoc
> +NOTE: Prometheus is currently the only monitoring system supported by Quarkus.
Officially supported; the rest of the monitoring systems are community supported in the Quarkiverse; the rest of the registries either need to be manually set up (like plain Java) or use a community extension (https://github.com/quarkiverse/quarkus-micrometer-registry)

2021-09-10 12:35 UTC, dupliaka approved these changes

2021-09-10 13:10 UTC, merged