BXMSDOC-2222 Install instructions on how to use and configure standalone decision central package are missing
emmurphy1/kie-docs pull request #40
Opened 2018-02-21 19:56 UTC by emmurphy1

The rendered doc is [here](http://file.ork.redhat.com/~emmurphy/BXMSDOC-2222a/#install-dc-standalone-proc).

I updated with comments in the jira, and I demoted the section to after Installing on EAP.

2018-02-22 13:24 UTC, jhrcek requested changes
Mostly ok, some comments inline

2018-02-22 13:24 UTC, jhrcek commented on docs/product-installation-guide/src/main/asciidoc/install-dc-standalone-proc.adoc
> +You can use the {CENTRAL} standalone JAR file to install {CENTRAL} on an application server other than {EAP}. This installation method does not require a separate server installation.
Talking about installation is a bit misleading in the case of standalone jar. The point of standalone jar is that installation is not need it. You just *run* it.

How about
You can use {CENTRAL} standalone jar file to run {CENTRAL} without needing to deploy it to application server like {EAP}.

2018-02-22 13:24 UTC, jhrcek commented on docs/product-installation-guide/src/main/asciidoc/install-standalone-properties-con.adoc
> +When you install standalone {KIE_SERVER}, you can use the properties listed in this section in the following command:
We don't have standalone {KIE_SERVER} - just standalone {CENTRAL}

2018-02-26 06:06 UTC, jhrcek requested changes
Just 2 small issues to go..

2018-02-26 06:06 UTC, jhrcek commented on docs/product-installation-guide/src/main/asciidoc/install-dc-standalone-proc.adoc
> +controllerUser=rest-all
If I recall correctly the 'rest-all' is no longer valid. You need the role 'kie-server' to make this work. So please change the line `controllerUser=rest-all` to `controllerUser=kie-server`

2018-02-26 06:06 UTC, jhrcek commented on docs/product-installation-guide/src/main/asciidoc/install-standalone-properties-con.adoc
> +* `org.kie.demo`: Enables external clone of a demo application from GitHub.
`org.kie.demo` should be removed, because it's no longer valid.

2018-02-27 05:44 UTC, jhrcek reviewed
Two small corrections ..

2018-02-27 05:44 UTC, jhrcek commented on docs/product-installation-guide/src/main/asciidoc/install-standalone-properties-con.adoc
> +* `org.kie.server.controller`: URL for connecting with a Kie Server Controller, for example: `org.kie.server.controller` - `ws://localhost:8080/decision-central/websocket/controller`.
Please remove the name of the property from the example, it looks kind of confusing:
```
for example: `org.kie.server.controller` - `ws://localhost:8080/decision-central/websocket/controller`.

-> 
for example:  `ws://localhost:8080/decision-central/websocket/controller`.
```

2018-02-27 12:24 UTC, jhrcek commented on docs/product-installation-guide/src/main/asciidoc/run-standalone-properties-con.adoc
> +rhdm-7.0.0.GA-decision-central-standalone.jar -s application-config.yaml -D<property>=<value> -D<property>=<value>
Sorry, I missed this in the previous jar: you're missing java -jar in the command to run the standalone jar, so the whole command should be java -jar rhdm-7.0.0.GA-decision-central-standalone.jar -s application-config.yaml -D<property>=<value> -D<property>=<value>

2018-02-27 12:33 UTC, jhrcek approved these changes
Looks good, thank you

2018-02-27 15:30 UTC, sterobin commented on docs/product-installation-guide/src/main/asciidoc/run-standalone-properties-con.adoc
> +In this command, `<property>` is a property from the following list and `<value>` is a value that you assign to that property.
Colon, "...that property:"

2018-02-27 15:30 UTC, sterobin commented on docs/product-installation-guide/src/main/asciidoc/run-standalone-properties-con.adoc
>  * `org.uberfire.nio.git.dir`: Location of the directory .niogit. Default: working directory
Some recurring style issues (per RH/IBM style) in this list of property descriptions:
- Put file/folder/config names in unicode quotes (`.niogit`, `.index`, `org.uberfire.admin`, etc.)
- Cap SSH throughout (some are and some aren't capped)
- Change the ones that start "Disable ..." to "Disables ..." for consistency.

2018-02-27 15:30 UTC, sterobin commented on docs/product-installation-guide/src/main/asciidoc/run-standalone-properties-con.adoc
>  If you plan to use RSA or any algorithm other than DSA, make sure you setup properly your Application Server to use Bouncy Castle JCE library.
It's not in this PR, but around here in the output is the following description of a property:
Passphrase to access your Operating Systems public keystore when cloning git repositories with scp style URLs; e.g. git@github.com:user/repository.git.

Change to this:

Passphrase to access the public keystore of your Operating System when cloning git repositories with SCP style URLs. Example: git@github.com:user/repository.git.

2018-02-27 15:30 UTC, sterobin commented on docs/product-installation-guide/src/main/asciidoc/run-standalone-properties-con.adoc
>  * `org.kie.verification.disable-dtable-realtime-verification`: Disables the realtime validation and verification of decision tables. Default: false
"of guided decision tables" (for clarity, since this feature doesn't apply to uploaded decision tables)

2018-02-27 15:49 UTC, sterobin commented on docs/product-installation-guide/src/main/asciidoc/run-dc-standalone-proc.adoc
> +. Create the `application-users.properties` file. Include an administrative user and if this {CENTRAL} instance will be a controller for {KIE_SERVER}, include a controller user, for example:
Forgot to mention that the structure "for example:" comes up several times. Technically IBM calls for complete sentences before colons like this (avoiding things like "the following", etc.). As you know, of course. What I often do is just put "Example" on a new line above the code sample. Makes it pretty scannable as well. I don't particularly care per se. You can keep as is or adjust if you like. Just pointing it out.

2018-02-27 16:19 UTC, merged